sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t malware94/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true malware94/docker-react npm run test -- --coverage